M48
; DRILL file {KiCad 7.0.7} date Sun Oct 29 13:34:45 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-10-29T13:34:45+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0295
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0591
%
G90
G05
T1
X6.1654Y-5.7096
X6.1654Y-5.8179
T2
X5.4331Y-5.8465
X5.6693Y-5.8465
T0
M30
