M48
; DRILL file {KiCad 8.0.5} date 2024-11-15T14:38:43+0000
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-11-15T14:38:43+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X4.1449Y-3.1593
X4.1449Y-3.3502
T2
X4.0256Y-3.1474
X4.0256Y-3.362
M30
